name: 'S3 Build Artifact Uploader'
description: 'Uploads build artifacts to AWS S3'
author: 'anilrajrimal'
inputs:
  aws-access-key-id:
    description: 'The AWS Access Key ID for authentication'
    required: true
  aws-secret-access-key:
    description: 'The AWS Secret Access Key for authentication'
    required: true
  aws-region:
    description: 'The AWS region where your S3 bucket is located'
    required: true
  s3-bucket-name:
    description: 'The S3 bucket to upload the build artifact to'
    required: true
  project-name:
    description: 'The name of the project'
    required: true
  zip-name:
    description: 'The name of the zip file to create and upload'
    required: true

runs:
  using: 'composite'
  steps:
    - name: Run Bash script
      shell: bash
      run: entrypoint.sh
      env:
        INPUT_AWS_ACCESS_KEY_ID: ${{ inputs.aws-access-key-id }}
        INPUT_AWS_SECRET_ACCESS_KEY: ${{ inputs.aws-secret-access-key }}
        INPUT_AWS_REGION: ${{ inputs.aws-region }}
        INPUT_S3_BUCKET_NAME: ${{ inputs.s3-bucket-name }}
        INPUT_PROJECT_NAME: ${{ inputs.project-name }}
        INPUT_ZIP_NAME: ${{ inputs.zip-name }}

branding:
  icon: "arrow-up-circle"
  color: "green"
